### ISSUE TITLE
display a message if the dialog name already exists.

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/dialog-tool#1]
If you try to create a dialog with an existing name you get an error in the console but nothing in the UI. We should not allow users to use an existing name.

**Comment by germanattanasio** [comment]
Assigning this to @Lhuihui. Let me know if you need help

**Comment by chinghuachen** [comment]
I didn't notice I had to even provide a name, and apparently it is mandatory. So please also display a message if the user fails to enter a name for the dialog.

**Comment by germanattanasio** [comment]
:+1:

**Comment by Lhuihui** [comment]
so it's done?

**Comment by germanattanasio** [comment]
yeah
