### ISSUE TITLE
CloudFoundry CLI deploy instructions need to be updated.

### ISSUE THREAD

**Issue by EmergentBehavior** [watson-developer-cloud/dialog-tool#10]
The `create` command fails:

`$ cf create-service dialog beta dialog-service-beta`

results in:

`Creating service instance dialog-service-beta in org XXX@YYY.com / space dev as XXX@YYY.com...
FAILED
Could not find plan with name beta`

**Comment by germanattanasio** [comment]
It should be:

```
cf create-service dialog standard dialog-service
```

**Comment by EmergentBehavior** [comment]
Great, thanks!

**Comment by EmergentBehavior** [comment]
@germanattanasio Actually it failed again with new command when I tried to push. It worked when I updated it to this before pushing again:

`cf create-service dialog standard dialog-service-standard`

**Comment by germanattanasio** [comment]
Cool.
