### ISSUE TITLE
How to actually create a dialog?

### ISSUE THREAD

**Issue by EmergentBehavior** [watson-developer-cloud/dialog-tool#12]
My apologies if this is covered elsewhere, but I do not see a way to create a dialog with this tool, only upload an existing dialog XML file.

The documentation refers to a Java dialog creation applet, but I cannot find that anywhere. Other parts of the documentation indicate this `dialog-tool` should be used to create the dialog...which leads me to my first problem.

Are we supposed to create the dialog file by hand now?

I ask here because at the very least the README.md for this project should be more clear how to use this feature or if it is not yet built yet.

**Comment by germanattanasio** [comment]
>  My apologies if this is covered elsewhere, but I do not see a way to create a dialog with this tool, only upload an existing dialog XML file.

Right now, there is no tool to create a dialog :pensive: so you need to do it by hand  

> The documentation refers to a Java dialog creation applet, but I cannot find that anywhere. 

There used to be an Applet but that is being replaced with a web app. _I don't know the ETA_ 

> Other parts of the documentation indicate this dialog-tool should be used to create the dialog...which leads me to my first problem.

I'm going to contact the documentation team to let them know about this. :bowtie:

> Are we supposed to create the dialog file by hand now?

yes

> I ask here because at the very least the README.md for this project should be more clear how to use this feature or if it is not yet built yet.

I'm going to combine this project with the `dialog-nodejs` over the weekend. That will change the UX so I will be updating the README also.

**Comment by EmergentBehavior** [comment]
Thanks so much @germanattanasio for clearing this up :)

**Comment by doxxon** [comment]
This is massively confusing as the title of the app indicates that it is a: "Tool to create, manage, and interact with dialogs for the IBM Watson Dialog Service"

Instructions on creating the dialog can be found here:
https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/dialog/tutorial_tutorials.shtml
