### ISSUE TITLE
Unable to run the Dialog tool locally

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/dialog-tool#25]
Hello I have downloaded the Dialog tool . 
Unfortunately I cannot run it locally and I get the following messages : 
Does it run for you ? 

```
$ node app.js
/Users/philippecomte/Documents/ALGE2016/WATSON_SERVICES_BLUEMIX/Dialog_Services/dialog-tool-master/config/express.js:26
  app.use(express.static(__dirname + '/../public'));
     ^

TypeError: Cannot read property 'use' of undefined
    at module.exports (/Users/philippecomte/Documents/ALGE2016/WATSON_SERVICES_BLUEMIX/Dialog_Services/dialog-tool-master/config/express.js:26:6)
    at Object.<anonymous> (/Users/philippecomte/Documents/ALGE2016/WATSON_SERVICES_BLUEMIX/Dialog_Services/dialog-tool-master/app.js:20:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by nfriedly** [comment]
That's strange... Could you try running a few commands and paste the output here:

``` sh
node -v
npm -v
npm ls --depth 0
npm start
```

**Comment by germanattanasio** [comment]
Did you run `npm install` ?

**Comment by PhilippeComte** [comment]
Here are the results of the commands : 

Last login: Wed Feb 17 19:13:50 on ttys000 
PCMacBook-Pro:~ philippecomte$ cd /Users/philippecomte/Applications/DialogServices/dialogtoolmaster 
PCMacBook-Pro:dialogtoolmaster philippecomte$ npm install 
PCMacBook-Pro:dialogtoolmaster philippecomte$ npm --version 
2.14.12 
PCMacBook-Pro:dialogtoolmaster philippecomte$ node -v 
v4.2.4 
PCMacBook-Pro:dialogtoolmaster philippecomte$ npm -v 
2.14.12 
PCMacBook-Pro:dialogtoolmaster philippecomte$ npm ls --depth 0 
DialogTool@0.1.1 /Users/philippecomte/Applications/DialogServices/dialogtoolmaster 
├── body-parser@1.14.2 
├── errorhandler@1.4.3 
├── express@4.13.4 
├── http-auth@2.2.8 
├── jade@1.11.0 
└── request@2.67.0 

PCMacBook-Pro:dialogtoolmaster philippecomte$ npm start 

> DialogTool@0.1.1 start /Users/philippecomte/Applications/DialogServices/dialogtoolmaster 
> node app.js 

/Users/philippecomte/Applications/DialogServices/dialogtoolmaster/config/express.js:26 
app.use(express.static(__dirname + '/../public')); 
^ 

TypeError: Cannot read property 'use' of undefined 
at module.exports (/Users/philippecomte/Applications/DialogServices/dialogtoolmaster/config/express.js:26:6) 
at Object.<anonymous> (/Users/philippecomte/Applications/DialogServices/dialogtoolmaster/app.js:20:16) 
at Module._compile (module.js:435:26) 
at Object.Module._extensions..js (module.js:442:10) 
at Module.load (module.js:356:32) 
at Function.Module._load (module.js:313:12) 
at Function.Module.runMain (module.js:467:10) 
at startup (node.js:136:18) 
at node.js:963:3 

npm ERR! Darwin 15.3.0 
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" 
npm ERR! node v4.2.4 
npm ERR! npm v2.14.12 
npm ERR! code ELIFECYCLE 
npm ERR! DialogTool@0.1.1 start: `node app.js` 
npm ERR! Exit status 1 
npm ERR! 
npm ERR! Failed at the DialogTool@0.1.1 start script 'node app.js'. 
npm ERR! This is most likely a problem with the DialogTool package, 
npm ERR! not with npm itself. 
npm ERR! Tell the author that this fails on your system: 
npm ERR! node app.js 
npm ERR! You can get their info via: 
npm ERR! npm owner ls DialogTool 
npm ERR! There is likely additional logging output above. 

npm ERR! Please include the following file with any support request: 
npm ERR! /Users/philippecomte/Applications/DialogServices/dialogtoolmaster/npm-debug.log 
PCMacBook-Pro:dialogtoolmaster philippecomte$

**Comment by nfriedly** [comment]
So that all looks right (except for the error where it fails to start). 

Can you try deleting the entire folder, re-downloading it, and then running `npm install` and `npm start` again and let me know if it does anything different?

**Comment by PhilippeComte** [comment]
Hello , 

Ok I'll do that . 
The way I did it was to download dialog-tool-master-.zip, unzip it and try to run the app. 

At what point should I run npm install ? 
pointing to the zip file ?

**Comment by nfriedly** [comment]
1. download & unzip
2. enter directory with unzipped files
3. run `npm install`
4. run `npm start`

**Comment by PhilippeComte** [comment]
Hello , 
I have repeated the steps in the prescribed order and it works .
Many thanks for your help.

**Comment by nfriedly** [comment]
You're welcome. I think it must have been a corrupted download or something along those lines.

**Comment by PhilippeComte** [comment]
Hello Nathan, 

I have submitted a new issue . As I was not able to attach an image , 
I attach it below : 
the issue is about how to get an answer and use the user interface. 
Many thanks. 

Cordialement 
Philippe Comte 
+33 676861847 

----- Mail original -----

De: "Nathan Friedly" notifications@github.com 
À: "watson-developer-cloud/dialog-tool" dialog-tool@noreply.github.com 
Cc: "PhilippeComte" philippe_comte@laposte.net 
Envoyé: Jeudi 18 Février 2016 14:16:32 
Objet: Re: [dialog-tool] Unable to run the Dialog tool locally (#25) 

You're welcome. I think it must have been a corrupted download or something along those lines.
