### ISSUE TITLE
what is dialog_id

### ISSUE THREAD

**Issue by srijack** [watson-developer-cloud/dialog-tool#28]
Hi

Im following the steps given in GitHub.
One of the steps says -
$ cf se application-name DIALOG_ID dialog-id

And it also says -
If you don't have a  dialog_id  you can create one using the dialog-tool

but - I'm not able to understand what is dialog_id or how to really create dialog_id-
If it exists what can I locate it ?
Please help me.
Thanks-

**Comment by germanattanasio** [comment]
The `dialog_id` is something like: `9feb4349-bf69-43e6-bbd3-92b317e2ff31` and identifies your dialog flow.

When using the Dialog service you need to specify a dialog id. Take a look at [this](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/dialog/tutorial_tutorials.shtml) tutorial on how to use the service.

You should be able to create a dialog id using curl

``` bash
curl -u "{username}":"{password}" \
  -X POST
  --form file=@template.xml
  --form name=templateName
  "https://gateway.watsonplatform.net/dialog/api/v1/dialogs"
```

Where `template.xml` is an xml file describing your dialog.  
Example: https://github.com/watson-developer-cloud/dialog-tool/blob/master/dialogs/pizza_sample.xml

**Comment by germanattanasio** [comment]
See more info here https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/dialog/api/v1/#create-dialog

**Comment by srijack** [comment]
Thank you -

Why am I getting this warning.

C:\bluemix\dialog\dialog-nodejs-master>npm install

> DialogNodejsStarterApp@0.1.8 postinstall C:\bluemix\di
> alog\dialog-nodejs-master
> node dialogs/install-dialogs.js

WARNING: Missing credentials or VCAP_SERVICES. Not installing dialog files

**Comment by germanattanasio** [comment]
if you deploy the sample application in bluemix it will create the dialog
automatically but you need to make sure you have a dialog-service and it's
bound to your app

**Comment by srijack** [comment]
Hi 
I have bound the service to the app.
But still credentials are not recognized.

console.log(credentials.username);
console.log(credentials.url);
    if (credentials && credentials.username) {
        dialogService.getDialogs(credentials, getDialogsCb);
    } else {
        console.warn('WARNING: Missing credentials or VCAP_SERVICES. Not installing dialog files.');
======result====
C:\bluemix\dialog\dialog-nodejs-master\dialogs>node inst
all-dialogs1.js
srinath
undefined
undefined

# WARNING: Missing credentials or VCAP_SERVICES. Not installing dialog files.

I tried logging credentials - seems like - it is not fetching ..
Can you please help me finding this - from where - install-dialog.js gets credentials from -
and what credentials are these.

**Comment by germanattanasio** [comment]
in the `install-dialog.js` replace

``` js
updateDialogFiles(bluemix.getServiceCreds('dialog'));
```

with:

``` js
updateDialogFiles({
  username: "USERNAME",
  password: "PASSWORD",
  version: 'v1'
});
```

where `USERNAME` and `PASSWORD` are your service credentials

**Comment by srijack** [comment]
Thank you so much - it worked.
I can now experiment.
