### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by monzua88** [watson-developer-cloud/dialog-tool#51]
Hi! I am trying running the tool locally and i have this error after installing npm:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"

npm ERR! node v4.4.7
npm ERR! npm v2.15.8

npm ERR! missing script: start

Hope you can help, thanks

**Comment by kognate** [comment]
I just cloned and ran the app using `npm start`.   You should make sure you have node installed and do an `npm install` before running start for the first time.  

Also, I'm not an expert, but you may be running into problems with Windows Real Time protection.  http://stackoverflow.com/questions/32965938/npm-error-windows-nt-how-to-resolve/34234584
