### ISSUE TITLE
Dialog service 

### ISSUE THREAD

**Issue by mexekanez** [watson-developer-cloud/dialog-tool#56]
Thank you for using the Watson Dialog service on Bluemix. We’d like to inform you that we are retiring the Watson Dialog service on August 9, 2016. On July 11, 2016, we released the generally available Watson Conversation service to replace Watson Dialog so that you can build more compelling bots and virtual agents.

Watson Conversation includes a rich set of tooling that allows users to easily create an intent classifier, extract entities, and design dialog flows without having knowledge of xml or coding. Please see this blog post for more details on Watson Conversation.

**Comment by germanattanasio** [comment]
The Dialog service was deprecated, please use conversation

**Comment by mexekanez** [comment]
@germanattanasio but conversation doesn't support expressions and ExecCode like it was in dialog.

```
<folder label="Library">
            <folder label="Live Content" id="folder_2447777">
                <output>
                    <prompt selectionType="RANDOM">
                        <item>Alright. Here are the {Sentiment} tweets about {Topic}:$ExecCode$showTweets(sender, "{Topic}", "{Sentiment}")</item>
                    </prompt>
                </output>
            </folder>
```

ex link (I need something similar): [https://github.com/nheidloff/facebook-watson-bot](https://github.com/nheidloff/facebook-watson-bot)
What solution can you suggest? 
I need a service like a dialog was

**Comment by mexekanez** [comment]
@germanattanasio  also could you PUT in readme.md that this service in Bluemix was deprecated a

**Comment by germanattanasio** [comment]
Good point Ivan, I think the Conversation has the feature you want it's just that it will different than what you are used to. @mitchmason can probably help you with your question.

**Comment by mexekanez** [comment]
@germanattanasio  If you meant this example 
[https://github.com/mitchmason/conversation-simple](https://github.com/mitchmason/conversation-simple)
I reviewed it also but nothing around requests to outside of watson conversation (for example if user asks bot to search some party in NYC how to do it without remote API//some service), as I see it (conversation) allows only one or few methods - [http://www.ibm.com/watson/developercloud/conversation/api/v1/?python#send_message](http://www.ibm.com/watson/developercloud/conversation/api/v1/?python#send_message)  

Dialog allowed to build some king of bot AI and get additional information outside of service

**Comment by germanattanasio** [comment]
We are going to release more functionality in the upcoming weeks. The whole idea of releasing a service like conversation was build something better than Dialog. We are working on it.
