### ISSUE TITLE
How do i create a dialog to ask user for a name?

### ISSUE THREAD

**Issue by Abhi150688** [watson-developer-cloud/dialog-tool#7]
How do i capture what the name of the user is? Since that field is dynamic. Name could be anything. The response would be My name is <<name>> or directly the name. 

How do i pick up the name?

**Comment by germanattanasio** [comment]
The dialog service [documentation](https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/dialog/#overview) has a [basic tutorial](https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/dialog/#tutorial_basic) that can help you.
